config/routes.rb
InStock::Application.routes.draw do
  resources :items do
    collection do
      get :search
      get :order
    end
  end

  devise_for :users

  resources :users, :except => :index, :path => '/'

  root :to => 'home#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :amazon_id, :name, :quantity, :reorder_threshold, :image_url

  belongs_to :user

  scope :out_of_stock, lambda {
    where('quantity < reorder_threshold')
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :display_name, :uniqueness => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :display_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :items

  def to_param
    display_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :redirect_to_user_page_if_logged_in, :only => :index

  def index
  end

  private
  def redirect_to_user_page_if_logged_in
    redirect_to current_user if current_user
  end
end

app/controllers/items_controller.rb
require 'amazon'

class ItemsController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!

  def create
    @item = Item.new(params[:item])
    @item.user = current_user

    if @item.save
      respond_with @item
    end
  end

  def index
    @items = current_user.items

    respond_with @items
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(params[:item])

    respond_with @item
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy

    respond_to do |format|
      format.json do
        render :json => { :status => "ok" }
      end
    end
  end

  def order
    req = Amazon.add_to_cart(
      [{
        'ASIN' => 'B004VGSVHS', 'Quantity' => 1},
        {'ASIN' => 'B001ET73CO', 'Quantity' => 2}
      ])

    res = req.get

    purchase_url = res.find('PurchaseURL').first

    respond_to do |format|
      format.json do
        render :json => {
          :purchase_url => purchase_url
        }
      end
    end
  end

  def search
    res = Amazon.api.search :all,
      keywords: params[:search],
      response_group: ['Images', 'ItemIds', 'ItemAttributes']

    items = res.find('Item')
    images = res.find('ImageSet')
    attrs = res.find('ItemAttributes')

    image_size = 'MediumImage'

    results = []

    3.times do |n|
      results << {
        :amazon_id => items[n]['ASIN'],
        :image => images[n][image_size]['URL'],
        :image_height => images[n][image_size]['Height']['__content__'],
        :image_width => images[n][image_size]['Width']['__content__'],
        :price => attrs[n]['ListPrice']['FormattedPrice'],
        :title => attrs[n]['Title'],
      }
    end

    respond_to do |format|
      format.json do
        render :json => results
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Sto.ck
%p Never waste time buying same boring items you always get.
%p If you find yourself buying the same items at the grocery store or on Amazon time and again start using Sto.ck to make your life easier.

%h4 Use cases
%ul
  %li Buying toiletries like toothpaste, toothbrushes, deodorant, razors, and toilet paper.
  %li Keeping your company's kitchen well stocked.
  %li Simple clothes like undershirts, socks, and underwear

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title InStock
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .flashes
    %p.alert= notice || alert

  .login_info
    -if current_user
      %span Logged in as #{current_user.display_name}
      |
      = link_to "Sign out", destroy_session_path(current_user), :method => :delete
    -else
      = link_to "Sign in", new_user_session_path

  = yield

app/views/users/show.haml
.item_manager

:coffeescript
  $ ->
    view = new InStock.Views.ItemManager

    $('.item_manager').replaceWith view.render().$el